add json/xlsx data

diff --git a/.github/workflows/data.yml b/.github/workflows/data.yml
--- a/.github/workflows/data.yml
+++ b/.github/workflows/data.yml
@@ -27,30 +27,64 @@ jobs:
           git config --global user.name "github-actions[bot]"
           sudo timedatectl set-timezone "Asia/Shanghai"
 
-      - name: Get models
+          sudo apt update
+          sudo apt install -y build-essential libtool pkgconf libzstd-dev liblzma-dev libssl-dev  # kmodule dependencies
+
+      - name: Get Release RR
         run: |
-          models="{"
-          WORK_PATH="files/initrd/opt/rr"
-          for M in $(find "${WORK_PATH}/model-configs" -maxdepth 1 -name \*.yml 2>/dev/null | sed 's/.*\///; s/\.yml//'); do
-            models+="\"${M}\":["
-            for V in $(yq eval '.productvers | explode(.) | to_entries | map([.key])[] | .[]' "${WORK_PATH}/model-configs/${M}.yml" 2>/dev/null | sort -r); do
-              models+="\"${V}\","
-            done
-            models="${models%,}],"
-          done
-          models="${models%,}}"
-          echo "${models}" >docs/models.json
+          REPO="${{ github.server_url }}/${{ github.repository }}"
+          PRERELEASE="false"
+
+          TAG=""
+          if [ "${PRERELEASE}" = "true" ]; then
+            TAG="$(curl -skL --connect-timeout 10 "${REPO}/tags" | grep /refs/tags/.*\.zip | head -1 | sed -r 's/.*\/refs\/tags\/(.*)\.zip.*$/\1/')"
+          else
+            LATESTURL="$(curl -skL --connect-timeout 10 -w %{url_effective} -o /dev/null "${REPO}/releases/latest")"
+            TAG="${LATESTURL##*/}"
+          fi
+          [ "${TAG:0:1}" = "v" ] && TAG="${TAG:1}"
+          rm -f rr-${TAG}.img.zip
+          STATUS=$(curl -kL --connect-timeout 10 -w "%{http_code}" "${REPO}/releases/download/${TAG}/rr-${TAG}.img.zip" -o "rr-${TAG}.img.zip")
+          if [ $? -ne 0 -o ${STATUS:-0} -ne 200 ]; then
+            echo "Download failed"
+            exit 1
+          fi
+          
+          unzip rr-${TAG}.img.zip -d "rr"
+
+          export TERM=xterm
+
+          sudo ./localbuild.sh create rr/ws rr/rr.img
+          if [ $? -ne 0 ]; then
+            echo "create failed"
+            exit 1
+          fi
+
+      - name: Get data
+        run: |
+          pip install -r scripts/requirements.txt
+          python scripts/func.py getmodels -w "rr/ws/initrd" -j "docs/models.json" -x "docs/models.xlsx"
+          python scripts/func.py getaddons -w "rr/ws" -j "docs/addons.json" -x "docs/addons.xlsx"
+          python scripts/func.py getmodules -w "rr/ws" -j "docs/modules.json" -x "docs/modules.xlsx"
+
+      - name: Upload to Artifacts
+        if: success() && inputs.push == false
+        uses: actions/upload-artifact@v4
+        with:
+          name: addons
+          path: |
+            docs/*.json
+            docs/*.xlsx
+          retention-days: 5
 
       - name: Check and Push
         if: success() && inputs.push == true
         run: |
             echo "Git push ..."
             git pull
-            status=$(git status -s | grep -E 'docs/models.json' | awk '{printf " %s", $2}')
+            status=$(git status -s | grep -E "docs" | awk '{printf " %s", $2}')
             if [ -n "${status}" ]; then
               git add ${status}
               git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
               git push -f
             fi
-
-  
diff --git a/.github/workflows/issues.yml b/.github/workflows/issues.yml
--- a/.github/workflows/issues.yml
+++ b/.github/workflows/issues.yml
@@ -155,9 +155,9 @@ jobs:
 
           export TERM=xterm
 
-          sudo ./localbuild.sh init rr/ws rr/rr.img
+          sudo ./localbuild.sh create rr/ws rr/rr.img
           if [ $? -ne 0 ]; then
-            echo "init failed"
+            echo "create failed"
             exit 1
           fi
 
@@ -166,10 +166,16 @@ jobs:
           # sudo sed -i '/^alias/i\set -x' rr/ws/initrd/opt/rr/menu.sh
                     
           [ -n "${{ env.language }}" ] && echo "${{ env.language }}.UTF-8" | sudo tee rr/ws/mnt/p1/.locale
-          
-          sudo ./localbuild.sh config "${MODEL}" "${VERSION}"
+
+          sudo ./localbuild.sh init
           if [ $? -ne 0 ]; then
-            echo "config failed"
+            echo "init failed"
+            exit 1
+          fi
+
+          sudo ./localbuild.sh make "${MODEL}" "${VERSION}"
+          if [ $? -ne 0 ]; then
+            echo "make failed"
             exit 1
           fi
 
