Update data.yml

diff --git a/.github/workflows/data.yml b/.github/workflows/data.yml
--- a/.github/workflows/data.yml
+++ b/.github/workflows/data.yml
@@ -36,58 +36,58 @@ jobs:
           sudo apt install -y build-essential libtool pkgconf libzstd-dev liblzma-dev libssl-dev  # kmodule dependencies
 
       - name: Get Release RR
-  run: |
-    REPO="https://github.com/offsoc/rr.git"
-    PRERELEASE="true"
+         run: |
+          REPO="https://github.com/offsoc/rr.git"
+          PRERELEASE="true"
 
-    TAG=""
-    if [ "${PRERELEASE}" = "true" ]; then
-      TAG="$(curl -skL --connect-timeout 10 "${REPO}/tags" | grep /refs/tags/.*\.zip | sed -r 's/.*\/refs\/tags\/(.*)\.zip.*$/\1/' | sort -rV | head -1)"
-    else
-      LATESTURL="$(curl -skL --connect-timeout 10 -w %{url_effective} -o /dev/null "${REPO}/releases/latest")"
-      TAG="${LATESTURL##*/}"
-    fi
+          TAG=""
+          if [ "${PRERELEASE}" = "true" ]; then
+          TAG="$(curl -skL --connect-timeout 10 "${REPO}/tags" | grep /refs/tags/.*\.zip | sed -r 's/.*\/refs\/tags\/(.*)\.zip.*$/\1/' | sort -rV | head -1)"
+          else
+          LATESTURL="$(curl -skL --connect-timeout 10 -w %{url_effective} -o /dev/null "${REPO}/releases/latest")"
+          TAG="${LATESTURL##*/}"
+          fi
 
-    if [ -z "${TAG}" ]; then
-      echo "Failed to fetch release tag."
-      exit 1
-    fi
+          if [ -z "${TAG}" ]; then
+          echo "Failed to fetch release tag."
+           exit 1
+          fi
 
-    if [ "${TAG:0:1}" = "v" ]; then
-      TAG="${TAG:1}"
-    fi
+           if [ "${TAG:0:1}" = "v" ]; then
+           TAG="${TAG:1}"
+           fi
 
-    echo "Downloading rr-${TAG}.img.zip..."
+           echo "Downloading rr-${TAG}.img.zip..."
 
-    rm -f "rr-${TAG}.img.zip"
-    STATUS=$(curl -kL --connect-timeout 10 -w "%{http_code}" "${REPO}/releases/download/${TAG}/rr-${TAG}.img.zip" -o "rr-${TAG}.img.zip")
+             rm -f "rr-${TAG}.img.zip"
+           STATUS=$(curl -kL --connect-timeout 10 -w "%{http_code}" "${REPO}/releases/download/${TAG}/rr-${TAG}.img.zip" -o "rr-${TAG}.img.zip")
 
-    if [ $? -ne 0 ] || [ ${STATUS:-0} -ne 200 ]; then
-      echo "Download failed with status ${STATUS}"
-      exit 1
-    fi
+          if [ $? -ne 0 ] || [ ${STATUS:-0} -ne 200 ]; then
+          echo "Download failed with status ${STATUS}"
+          exit 1
+          fi
 
-    echo "Successfully downloaded rr-${TAG}.img.zip"
+           echo "Successfully downloaded rr-${TAG}.img.zip"
 
-    echo "Unzipping rr-${TAG}.img.zip..."
-    unzip -q "rr-${TAG}.img.zip" -d "rr"
+            echo "Unzipping rr-${TAG}.img.zip..."
+           unzip -q "rr-${TAG}.img.zip" -d "rr"
 
-    if [ $? -ne 0 ]; then
-      echo "Failed to unzip rr-${TAG}.img.zip"
-      exit 1
-    fi
+           if [ $? -ne 0 ]; then
+          echo "Failed to unzip rr-${TAG}.img.zip"
+          exit 1
+          fi
 
-    export TERM=xterm
+           export TERM=xterm
 
-    echo "Running localbuild.sh..."
-    sudo ./localbuild.sh create rr/ws rr/rr.img
+          echo "Running localbuild.sh..."
+          sudo ./localbuild.sh create rr/ws rr/rr.img
+   
+             if [ $? -ne 0 ]; then
+               echo "localbuild.sh create failed"
+             exit 1
+              fi
 
-    if [ $? -ne 0 ]; then
-      echo "localbuild.sh create failed"
-        exit 1
-        fi
-
-        shell: /bin/bash
+           shell: /bin/bash
 
 
       - name: Get data
