fix something

diff --git a/.github/workflows/issues.yml b/.github/workflows/issues.yml
--- a/.github/workflows/issues.yml
+++ b/.github/workflows/issues.yml
@@ -121,7 +121,7 @@ jobs:
       - name: Run Build
         if: env.iscustom == 'true'
         run: |
-          # 累了, 毁灭吧
+          # 累了, 毁灭吧!
 
           REPO=${{ github.server_url }}/${{ github.repository }}
           MODEL=${{ env.model }}
@@ -146,10 +146,28 @@ jobs:
 
           export TERM=xterm
 
-          sudo ./localbuild.sh init rr rr/rr.img
-          sudo ./localbuild.sh config ${MODEL}
-          sudo ./localbuild.sh pack rr/rr.img
+          sudo ./localbuild.sh init rr/ws rr/rr.img
+          if [ $? -ne 0 ]; then
+            echo "init failed"
+            exit 1
+          fi
+
+          # sudo cp -rf files/initrd/opt/rr/* rr/ws/initrd/opt/rr/
+          # sudo sed -i "s/set -e/set -ex/" rr/ws/initrd/opt/rr/init.sh
+          # sudo sed -i '/^alias/i\set -x' rr/ws/initrd/opt/rr/menu.sh
           
+          sudo ./localbuild.sh config ${MODEL}
+          if [ $? -ne 0 ]; then
+            echo "config failed"
+            exit 1
+          fi
+
+          sudo ./localbuild.sh pack rr/rr.img
+          if [ $? -ne 0 ]; then
+            echo "pack failed"
+            exit 1
+          fi
+
           ls rr -al
           zip -9 "rr-${MODEL}-${TAG}-${{ github.run_id }}.img.zip" -j rr/rr.img
           
